package main;

/**
 * the query processor can translate the queries which are generated by the user
 * into transaction languages.
 * 
 * For example, the user chooses a stock for the transaction, the query will be
 * passed to the query processor and translated into SQL language, and the
 * database will understand what data is requested and send it to the user
 * */
public interface queryProcessor {
	/**
	 * 
	 * once user need to add personal information in their account processor
	 * need to put the user entry in the database
	 */
	boolean addPersonalInformation();

	/**if user want to change some personal information, after the changing,
	*all the personal information
	* should be stored in the database. Make
	* sure all the table which store personal information is updated //whenever
	* the data is changed.
	*/
	boolean changePersonalInformation();

	/** once user request for a stock information, the graphic generator
	* should request to the database traverse the database then return
	* related stock data.
	*/
	boolean viewPersonalInformation();

	/** if user delete some personal information like data of birth. The
	* related table in database should also change.
	*/
	boolean deletePersonalInformation();
}
